SRC=test1.cpp ../src/hostaddress.cpp ../include/hostaddress.h\
    ../src/tcpsocket.cpp ../include/tcpsocket.h\
    ../src/exeption.cpp ../include/exeption.h

all : test1

test1 : test1.cpp
	g++ -o test1 ${SRC}
